export default {
  name: 'galleryProject',
  title: 'Gallery Project',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'url',
      title: 'URL',
      type: 'url',
    },
    {
      name: 'seoTitle',
      title: 'SEO Title (Opcjonalnie: długa nazwa dla Google)',
      type: 'string',
      description: 'Jeśli wypełnisz, Google użyje tej nazwy zamiast krótkiego Title.',
    },
    {
      name: 'seoDescription',
      title: 'SEO Description (Opcjonalnie: długi, niewidzialny opis dla Google)',
      type: 'text',
      description: 'Niewidzialny na stronie, ale doskonały dla SEO. Pełen słów kluczowych kontekst.',
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'frontImage',
      title: 'Front Image (Unpainted)',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'paintedImage',
      title: 'Painted Image',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'techStack',
      title: 'Tech Stack (Select up to 4 technologies)',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          // AI / ML
          { title: 'Python', value: 'Python' },
          { title: 'FastAPI', value: 'FastAPI' },
          { title: 'LangChain', value: 'LangChain' },
          { title: 'LangGraph', value: 'LangGraph' },
          { title: 'Hugging Face', value: 'Hugging Face' },
          { title: 'PyTorch', value: 'PyTorch' },
          { title: 'TensorFlow', value: 'TensorFlow' },
          { title: 'OpenCV', value: 'OpenCV' },
          { title: 'Gemini', value: 'Gemini' },
          { title: 'Generative AI', value: 'Generative AI' },
          { title: 'Vector Database', value: 'Vector Database' },
          // Frontend
          { title: 'React', value: 'React' },
          { title: 'Next.js', value: 'Next.js' },
          { title: 'Three.js / R3F', value: 'Three.js' },
          { title: 'TypeScript', value: 'TypeScript' },
          { title: 'JavaScript', value: 'JavaScript' },
          { title: 'Tailwind CSS', value: 'Tailwind CSS' },
          { title: 'HTML5', value: 'HTML' },
          { title: 'CSS3', value: 'CSS' },
          // Backend & Databases
          { title: 'Node.js', value: 'Node.js' },
          { title: 'Express.js', value: 'Express.js' },
          { title: 'PostgreSQL', value: 'PostgreSQL' },
          { title: 'MongoDB', value: 'MongoDB' },
          { title: 'Supabase', value: 'Supabase' },
          { title: 'Redis', value: 'Redis' },
          { title: 'WebSockets', value: 'WebSockets' },
          { title: 'Socket.IO', value: 'Socket.IO' },
          // Web3 & Cloud
          { title: 'Solidity', value: 'Solidity' },
          { title: 'IPFS', value: 'IPFS' },
          { title: 'Web3.js / Ethers.js', value: 'Web3.js' },
          { title: 'Docker', value: 'Docker' },
          { title: 'Firebase', value: 'Firebase' },
          { title: 'Cloudinary', value: 'Cloudinary' },
          { title: 'AWS', value: 'AWS' },
          { title: 'Vercel / Netlify', value: 'Netlify' },
          // Legacy texture values (for backward compatibility)
          { title: 'React (Icon)', value: 'reactlogo.webp' },
          { title: 'JavaScript (Icon)', value: 'jslogo.webp' },
          { title: 'HTML (Icon)', value: 'htmllogo.webp' },
          { title: 'CSS (Icon)', value: 'csslogo.webp' },
          { title: 'Tailwind (Icon)', value: 'tailwindlogo.webp' },
          { title: 'Firebase (Icon)', value: 'firebaselogo.webp' },
          { title: 'Netlify (Icon)', value: 'netlifylogo.webp' },
        ],
        layout: 'grid',
      },
      validation: (Rule) => Rule.max(4),
    },
  ],
};
